name: LitterBox CI
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: npm ci and build artifacts
      run: |
        npm ci
        npm run build
        git config user.name github-actions
        git config user.email github-actions@github.com
        git --work-tree build add --all
        git commit -S -m "Automatic deploy action run by github-actions"
        git push origin HEAD:gh-pages --force
